In [ ]:
marks = [55, 90, 40, 70, 80]
bonus = 5

new_marks = []

for m in marks:
    new_marks.append(m+bonus)

print(new_marks)

[60, 95, 45, 75, 85]


In [ ]:
marks + 5

TypeError: can only concatenate list (not "int") to list

In [ ]:
import numpy as np
marks = np.array([55, 90, 40, 70, 80])
new_marks = marks + bonus
print(new_marks)

[60 95 45 75 85]


In [ ]:
a = [4,6,8,2,1]
type(a)

list

In [ ]:
np_a = np.array(a)
print(np_a)

[4 6 8 2 1]


In [ ]:
type(np_a)

numpy.ndarray

In [ ]:
# given a python list:
a = [3, 6, 1, 9]

b = []

for i in a:
    b.append(i * 2)

print(b)

[6, 12, 2, 18]


In [ ]:
a_np = np.array(a)
b_np = a_np*2
print(b_np)

[ 6 12  2 18]


In [ ]:
type(b_np)

numpy.ndarray

In [ ]:
a_np-2

array([ 1,  4, -1,  7])

In [ ]:
a_np/2

array([1.5, 3. , 0.5, 4.5])

In [ ]:
a = [[2, 4, 5],
     [6, 3, 1],
     [5, 7, 2]]
type(a)

list

In [ ]:
print(a)

[[2, 4, 5], [6, 3, 1], [5, 7, 2]]


In [ ]:
b = np.array(a)
print(b)

[[2 4 5]
 [6 3 1]
 [5 7 2]]


In [ ]:
type(b)

numpy.ndarray

In [ ]:
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [ ]:
a = np.zeros((4,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
a = np.ones(4)
print(a)

[1. 1. 1. 1.]


In [ ]:
a = np.ones((4,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [ ]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(2, 11, 2)

array([ 2,  4,  6,  8, 10])

In [ ]:
np.arange(5, 11)

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1, 32)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [ ]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

#Arithmetic Operations

In [ ]:
a = np.array([3, 5, 6])
b = np.array([5, 6, 1])

In [ ]:
print(a)

[3 5 6]


In [ ]:
print(b)

[5 6 1]


In [ ]:
a = [3, 5, 6]
b = [5, 6, 1]

# c = [8,11,7]
c = []

n = len(a)
for i in range(n):
    c.append(a[i] + b[i])

print(c)

[8, 11, 7]


In [ ]:
a + b

[3, 5, 6, 5, 6, 1]

In [ ]:
an = np.array(a)
bn = np.array(b)
print(an + bn)

[ 8 11  7]


In [ ]:
print(an-bn)

[-2 -1  5]


In [ ]:
print(a*b)

TypeError: can't multiply sequence by non-int of type 'list'

In [ ]:
print(an*bn)

[15 30  6]


In [ ]:
print(an**2)

[ 9 25 36]
